version: '3'
services:
  database:
    image: mysqla
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: asej
      MYSQL_DATABASE: achatdb   
    ports:
      - 3306:3306
    networks:
     - AppNet
     
  spring-boot:
    image: asej1/springprojet
    container_name: spring
    ports:
      - 8082:8082
    depends_on:
      - database
    networks:
      - AppNet 
    restart: on-failure     

networks:
  AppNet:
